apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - list:
      elements:
      - appName: cert-manager
        namespace: cert-manager
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      sources:
      - repoURL: https://charts.jetstack.io
        chart: '{{appName}}'
        targetRevision: 1.11.0
        helm:
          valueFiles:
          - $values/cert-manager/values.yaml
      - repoURL: https://github.com/kimfy/k8s-bootstrap.git
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
