apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - list:
      elements:
        - name: consul
          namespace: consul
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      sources:
      - repoURL: https://helm.releases.hashicorp.com
        chart: '{{appName}}'
        targetRevision: 1.0.4
        helm:
          valueFiles:
          - $values/consul/values.yaml
      - repoURL: https://github.com/kimfy/k8s-bootstrap.git
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
