apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source: 
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 0.23.0
    helm:
      parameters:
        - name: "installCRDs"
          value: "true"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

