apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: consul
    server: {{ .Values.spec.destination.server }}
  project: default
  source: 
    repoURL: https://helm.releases.hashicorp.com
    chart: consul
    targetRevision: 1.0.4
    helm:
      parameters:
        # This enables or disables Consul
        - name: "global.enabled"
          value: "false"

