{{- if .Values.vault.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  project: default
  source: 
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.23.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
